RR: Finds open port for CryoSPARC

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -2,6 +2,66 @@
 set -ex -o pipefail
 
 # =======================================
+# Find a port for CyroSPARC
+# =======================================
+
+# This finds an open port for CryoSPARC.
+# We don't want to directly use OOD's internal find_port 
+# because it seems like OOD will use the discovered port to 
+# proxy VNC (which we don't want!).  Here, I've copy-pasted
+# OOD's shell functions with some changes.
+my_find_port () {
+    local host=localhost
+    # The usual private port range for TCP
+    local min_port=49152
+    local max_port=65535
+    local port_range=($(shuf -i ${min_port}-${max_port}))
+    local retries=1 # number of retries over the port range if first attempt fails
+    for ((attempt=0; attempt<=$retries; attempt++)); do
+    for port in "${port_range[@]}"; do
+        if my_port_used "${host}:${port}"; then
+        continue
+        fi
+        echo "${port}"
+        return 0 # success
+    done
+    done
+    echo "error: failed to find available port in range ${min_port}..${max_port}" >&2
+    return 1 # failure
+}
+
+my_port_used () {
+    local port="${1#*:}"
+    local host=$((expr "${1}" : '\\(.*\\):' || echo "localhost") | awk 'END{print $NF}')
+    my_port_used_nc $host $port
+    status=$?
+    if [[ "$status" == "0" ]] || [[ "$status" == "1" ]]; then
+        return $status
+    fi
+    return 127
+}
+
+my_port_used_nc(){
+    nc -w 2 "$1" "$2" < /dev/null > /dev/null 2>&1
+}
+
+my_port=$(my_find_port)
+
+# Check the result 
+# TODO: If this check fails, the job termintates with 
+# when after.sh is finished (which is good) but it the job
+# card says "Completed" instead of showing a failure
+# The error is still clear from output.log, but it would be
+# nice to make this as a failure on the job card
+regex='^[0-9]+$'
+if [[ $my_port =~ $regex ]]; then
+  echo "Found available port for CryoSPARC: $my_port"
+else
+  echo "error: Couldn't find available port for CryoSPARC: $my_port"
+  exit 1
+fi
+
+# =======================================
 # For VNC
 # =======================================
 
@@ -29,8 +89,8 @@ xfce4-panel --sm-client-disable &
 unset DBUS_SESSION_BUS_ADDRESS
 export CRYOSPARC_LICENSE_ID="<%= context.license_id %>"
 export CRYOSPARC_MASTER_HOSTNAME="$host"
-#export CRYOSPARC_BASE_PORT="$port"
-export CRYOSPARC_BASE_PORT="41001"
+# Don't use OOD's find_port here.  See explanation above.
+export CRYOSPARC_BASE_PORT="$my_port"
 export CRYOSPARC_DB_PATH="<%= context.db_path %>"
 
 # Cleanup.  TODO: See how much of this is strictly required
